global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['router:8000', 'localhost:8000']

  - job_name: 'manager'
    static_configs:
      - targets: ['manager:8001', 'localhost:8001']

