global:
  scrape_interval: 10s
  evaluation_interval: 15s
  scrape_timeout: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'router'
    metrics_path: /metrics
    static_configs:
      - targets: ['router:8000']
  - job_name: 'manager'
    metrics_path: /metrics
    static_configs:
      - targets: ['manager:8001']   
  - job_name: 'backends'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend1:8101','backend2:8102','backend3:8103']
