global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['router:8000']
  - job_name: 'manager'
    static_configs:
      - targets: ['manager:8001']
  - job_name: 'backend1'
    static_configs:
      - targets: ['backend1:8101']
  - job_name: 'backend2'
    static_configs:
      - targets: ['backend2:8102']
  - job_name: 'backend3'
    static_configs:
      - targets: ['backend3:8103']
